<a href="https://www.kaggle.com/code/mstadorikhatun/mlb-2-class-5-assignment-adori?scriptVersionId=346976263" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [109]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [110]:
import numpy as np
import pandas as pd

In [111]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [112]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [113]:
[10, 20, 30]
# 1D Array
x = np.array([10.5,20,30], dtype = float)
x

array([10.5, 20. , 30. ])

In [114]:
# 2D Array
y = np.array([[10,20,30],[40,50,60]])
y

array([[10, 20, 30],
       [40, 50, 60]])

In [115]:
# 3D Array
z = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
z

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [116]:
# 4D Array
p = np.array([[[[10,20],[30,40]],[[50,60],[70,80]]],[[[90,100],[110,120]],[[130,140],[150,160]]]])
p

array([[[[ 10,  20],
         [ 30,  40]],

        [[ 50,  60],
         [ 70,  80]]],


       [[[ 90, 100],
         [110, 120]],

        [[130, 140],
         [150, 160]]]])

# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [117]:
# arrange for array creation
x = np.arange(5,100)
print(x)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


Reshape

In [118]:
# 2D Array
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
# 3D Array
np.arange(60).reshape(3,4,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [120]:
# 4D Array
np.arange(96).reshape(4,4,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]],


       [[[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53]],

        [[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]],


       [[[72, 73, 74],
         [75, 76, 77]],

        [[78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89]],

        [[90, 91, 92],
         [93, 94, 95]]]])

# create array using ones and zeros

In [121]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [122]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# using random

In [123]:
np.round(np.random.random((4,6))*10000)

array([[7448.,  194., 8104., 2697., 8338., 4422.],
       [ 305., 4541., 3024.,  195., 3517., 5776.],
       [ 243., 5079.,   66., 6058., 5897., 3507.],
       [2720., 6672., 8026., 4398., 9536., 5223.]])

# using linspace

In [124]:
np.linspace(1,50,10,dtype = int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

# create 1D array of tip from tips dataframe

In [125]:
tip = tips['tip'].to_numpy()
print(tip)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [126]:
data = tips[['total_bill','tip']].to_numpy()
data

array([[16.99,  1.01],
       [10.34,  1.66],
       [21.01,  3.5 ],
       [23.68,  3.31],
       [24.59,  3.61],
       [25.29,  4.71],
       [ 8.77,  2.  ],
       [26.88,  3.12],
       [15.04,  1.96],
       [14.78,  3.23],
       [10.27,  1.71],
       [35.26,  5.  ],
       [15.42,  1.57],
       [18.43,  3.  ],
       [14.83,  3.02],
       [21.58,  3.92],
       [10.33,  1.67],
       [16.29,  3.71],
       [16.97,  3.5 ],
       [20.65,  3.35],
       [17.92,  4.08],
       [20.29,  2.75],
       [15.77,  2.23],
       [39.42,  7.58],
       [19.82,  3.18],
       [17.81,  2.34],
       [13.37,  2.  ],
       [12.69,  2.  ],
       [21.7 ,  4.3 ],
       [19.65,  3.  ],
       [ 9.55,  1.45],
       [18.35,  2.5 ],
       [15.06,  3.  ],
       [20.69,  2.45],
       [17.78,  3.27],
       [24.06,  3.6 ],
       [16.31,  2.  ],
       [16.93,  3.07],
       [18.69,  2.31],
       [31.27,  5.  ],
       [16.04,  2.24],
       [17.46,  2.54],
       [13.94,  3.06],
       [ 9.

In [127]:
data.shape

(244, 2)

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [128]:
x = np.arange(15)
y = np.arange(25).reshape(5,5)
z = np.arange(64).reshape(4,4,4)

In [129]:
x.ndim

1

In [130]:
y.ndim

2

In [131]:
z.ndim

3

Shape

In [132]:
x.shape

(15,)

In [133]:
y.shape

(5, 5)

In [134]:
z.shape

(4, 4, 4)

Size

In [135]:
np.size(x)

15

In [136]:
np.size(y)

25

In [137]:
np.size(z)

64

Itemsize

In [138]:
x.itemsize

8

In [139]:
y.itemsize

8

In [140]:
z.itemsize

8

# change data type and memory size of any np-array using astype()

In [141]:
data = data.astype(np.float32)
data.itemsize

4

In [142]:
print(data.dtype)

float32


# create 2 same dimensional array and do scalar and vector operations

In [143]:
p = np.arange(15).reshape(3,5)
q = np.arange(15,30).reshape(3,5)
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [144]:
q


array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

Scalar operations

In [145]:
p * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [146]:
q + 2

array([[17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]])

In [147]:
p - 2

array([[-2, -1,  0,  1,  2],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [148]:
q ** 4

array([[ 50625,  65536,  83521, 104976, 130321],
       [160000, 194481, 234256, 279841, 331776],
       [390625, 456976, 531441, 614656, 707281]])

In [149]:
p / 2

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ]])

Vector operations

In [150]:
r = p + q
r

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [151]:
s = q -  p
s

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [152]:
t = q * q
t

array([[225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576],
       [625, 676, 729, 784, 841]])

In [153]:
u = p / q
u

array([[0.        , 0.0625    , 0.11764706, 0.16666667, 0.21052632],
       [0.25      , 0.28571429, 0.31818182, 0.34782609, 0.375     ],
       [0.4       , 0.42307692, 0.44444444, 0.46428571, 0.48275862]])

# find minimun and maximum tip

In [154]:
tip

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

In [155]:
np.min(tip)

np.float64(1.0)

In [156]:
np.max(tip)

np.float64(10.0)

# find average total_bill and average tip

In [157]:
np.mean(tip)

np.float64(2.99827868852459)

In [158]:
np.mean(tips['total_bill'])

np.float64(19.78594262295082)

# find median total_bill

In [159]:
np.median(tips['total_bill'])

np.float64(17.795)

# find standard deviasion and variance of tip

In [160]:
np.std(tip)

np.float64(1.3807999538298954)

In [161]:
np.var(tip)

np.float64(1.9066085124966412)

# find log values of tip

In [162]:
np.log(tip)

array([0.00995033, 0.5068176 , 1.25276297, 1.19694819, 1.28370777,
       1.54968791, 0.69314718, 1.137833  , 0.67294447, 1.17248214,
       0.53649337, 1.60943791, 0.45107562, 1.09861229, 1.10525683,
       1.36609165, 0.51282363, 1.31103188, 1.25276297, 1.20896035,
       1.40609699, 1.01160091, 0.80200159, 2.0255132 , 1.1568812 ,
       0.85015093, 0.69314718, 0.69314718, 1.45861502, 1.09861229,
       0.37156356, 0.91629073, 1.09861229, 0.89608802, 1.18478998,
       1.28093385, 0.69314718, 1.12167756, 0.83724752, 1.60943791,
       0.80647587, 0.93216408, 1.11841492, 0.27763174, 1.7227666 ,
       1.09861229, 1.60943791, 1.79175947, 0.71783979, 1.09861229,
       0.91629073, 0.95551145, 1.64865863, 0.44468582, 1.46787435,
       1.25561604, 1.09861229, 0.40546511, 0.56531381, 1.90657514,
       1.16627094, 0.69314718, 0.68309684, 1.32441896, 0.97077892,
       1.14740245, 0.90421815, 0.        , 0.69813472, 0.73716407,
       0.67803354, 1.09861229, 1.1442228 , 1.60943791, 0.78845

In [163]:
np.exp(tip)

array([2.74560102e+00, 5.25931084e+00, 3.31154520e+01, 2.73851255e+01,
       3.69660528e+01, 1.11052160e+02, 7.38905610e+00, 2.26463796e+01,
       7.09932707e+00, 2.52796570e+01, 5.52896148e+00, 1.48413159e+02,
       4.80664819e+00, 2.00855369e+01, 2.04912917e+01, 5.04004448e+01,
       5.31216780e+00, 4.08538065e+01, 3.31154520e+01, 2.85027336e+01,
       5.91454698e+01, 1.56426319e+01, 9.29986608e+00, 1.95862897e+03,
       2.40467536e+01, 1.03812366e+01, 7.38905610e+00, 7.38905610e+00,
       7.36997937e+01, 2.00855369e+01, 4.26311452e+00, 1.21824940e+01,
       2.00855369e+01, 1.15883467e+01, 2.63113393e+01, 3.65982344e+01,
       7.38905610e+00, 2.15419027e+01, 1.00744247e+01, 1.48413159e+02,
       9.39333129e+00, 1.26796710e+01, 2.13275572e+01, 3.74342138e+00,
       2.70426407e+02, 2.00855369e+01, 1.48413159e+02, 4.03428793e+02,
       7.76790111e+00, 2.00855369e+01, 1.21824940e+01, 1.34637380e+01,
       1.81272242e+02, 4.75882125e+00, 7.67075393e+01, 3.34482678e+01,
      

# apply round, floor and ceil operation on tip array

In [164]:
tip_arr = np.array(tip)
np.round(tip_arr)

array([ 1.,  2.,  4.,  3.,  4.,  5.,  2.,  3.,  2.,  3.,  2.,  5.,  2.,
        3.,  3.,  4.,  2.,  4.,  4.,  3.,  4.,  3.,  2.,  8.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  4.,  2.,  3.,  2.,
        5.,  2.,  3.,  3.,  1.,  6.,  3.,  5.,  6.,  2.,  3.,  2.,  3.,
        5.,  2.,  4.,  4.,  3.,  2.,  2.,  7.,  3.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  3.,  3.,  3.,  2.,  5.,  2.,  5.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  4.,  3.,  5.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  3.,
        4.,  2.,  4.,  4.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  5.,
        2.,  2.,  3.,  2.,  2.,  2.,  2.,  3.,  4.,  1.,  2.,  2.,  2.,
        2.,  3.,  2.,  2.,  3.,  1.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  2.,  5.,
        5.,  4.,  3.,  2.,  4.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  2.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  4.,  4

In [165]:
np.floor(tip_arr)

array([ 1.,  1.,  3.,  3.,  3.,  4.,  2.,  3.,  1.,  3.,  1.,  5.,  1.,
        3.,  3.,  3.,  1.,  3.,  3.,  3.,  4.,  2.,  2.,  7.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  3.,  2.,  3.,  2.,
        5.,  2.,  2.,  3.,  1.,  5.,  3.,  5.,  6.,  2.,  3.,  2.,  2.,
        5.,  1.,  4.,  3.,  3.,  1.,  1.,  6.,  3.,  2.,  1.,  3.,  2.,
        3.,  2.,  1.,  2.,  2.,  1.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  2.,  3.,  3.,  1.,  5.,  2.,  5.,  2.,  4.,  5.,  3.,  3.,
        3.,  1.,  4.,  3.,  4.,  4.,  1.,  3.,  1.,  2.,  3.,  2.,  3.,
        4.,  1.,  4.,  4.,  3.,  4.,  3.,  1.,  4.,  2.,  4.,  3.,  5.,
        1.,  1.,  2.,  2.,  1.,  2.,  2.,  2.,  4.,  1.,  2.,  2.,  2.,
        1.,  2.,  1.,  2.,  3.,  1.,  2.,  2.,  2.,  2.,  3.,  6.,  5.,
        5.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  5.,
        5.,  3.,  2.,  2.,  3.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  1.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  3.,  3

In [166]:
np.ceil(tip_arr)

array([ 2.,  2.,  4.,  4.,  4.,  5.,  2.,  4.,  2.,  4.,  2.,  5.,  2.,
        3.,  4.,  4.,  2.,  4.,  4.,  4.,  5.,  3.,  3.,  8.,  4.,  3.,
        2.,  2.,  5.,  3.,  2.,  3.,  3.,  3.,  4.,  4.,  2.,  4.,  3.,
        5.,  3.,  3.,  4.,  2.,  6.,  3.,  5.,  6.,  3.,  3.,  3.,  3.,
        6.,  2.,  5.,  4.,  3.,  2.,  2.,  7.,  4.,  2.,  2.,  4.,  3.,
        4.,  3.,  1.,  3.,  3.,  2.,  3.,  4.,  5.,  3.,  2.,  4.,  4.,
        3.,  3.,  3.,  4.,  2.,  5.,  3.,  6.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  5.,  4.,  5.,  4.,  2.,  3.,  2.,  3.,  3.,  3.,  4.,
        5.,  2.,  5.,  5.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  6.,
        2.,  2.,  3.,  3.,  2.,  3.,  2.,  3.,  5.,  2.,  2.,  2.,  3.,
        2.,  3.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  3.,  2.,  2.,  6.,
        5.,  4.,  3.,  2.,  4.,  3.,  2.,  2.,  3.,  4.,  3.,  5.,  2.,
        2., 10.,  4.,  6.,  4.,  4.,  4.,  2.,  2.,  4.,  4.,  4

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [167]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [168]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [169]:
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

Indexing 1D Array

In [170]:
x[0]

np.int64(0)

In [171]:
x[6]

np.int64(6)

In [172]:
x[-7]

np.int64(8)

In [173]:
x[-3]

np.int64(12)

In [174]:
x[-13]

np.int64(2)

Slicing 1D Array

In [175]:
x[:5]

array([0, 1, 2, 3, 4])

In [176]:
x[3: 8]

array([3, 4, 5, 6, 7])

In [177]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [178]:
x[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [179]:
x[-8:-3]

array([ 7,  8,  9, 10, 11])

Indexing 2D Array

In [180]:
y[0,4]

np.int64(4)

In [181]:
y[2,3]

np.int64(13)

In [182]:
y[-1,0]

np.int64(20)

In [183]:
y[-1,-3]

np.int64(22)

In [184]:
y[2]

array([10, 11, 12, 13, 14])

Slicing 2D Array


In [185]:
y[:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [186]:
y[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [187]:
y[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [188]:
y[-3:-1,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [189]:
y[:,::-2]

array([[ 4,  2,  0],
       [ 9,  7,  5],
       [14, 12, 10],
       [19, 17, 15],
       [24, 22, 20]])

Indexing 3D Array

In [190]:
z[2,0,3]

np.int64(35)

In [191]:
z[-3,-2,-4]

np.int64(24)

In [192]:
z[1,-1,2]

np.int64(30)

In [193]:
z[-3,0,-3]

np.int64(17)

In [194]:
z[2,-2,2]

np.int64(42)

Slicing 3D Array

In [195]:
z[0,1:2,:]

array([[4, 5, 6, 7]])

In [196]:
z[0:2,1:2,1:3]

array([[[ 5,  6]],

       [[21, 22]]])

In [197]:
z[::-1,:,:]

array([[[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [198]:
z[:,0:2,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]]])

In [199]:
z[1:3,1:3,1:3]

array([[[21, 22],
        [25, 26]],

       [[37, 38],
        [41, 42]]])

# stacking and spliting

In [200]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

In [201]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [202]:
e

array([[28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

# use hstack() and vstack()

In [203]:
np.hstack((e,d))

array([[28, 29, 30, 31, 32, 33, 34, 35, 36,  0,  1,  2,  3,  4,  5,  6,
         7,  8],
       [37, 38, 39, 40, 41, 42, 43, 44, 45,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [46, 47, 48, 49, 50, 51, 52, 53, 54, 18, 19, 20, 21, 22, 23, 24,
        25, 26]])

In [204]:
np.vstack((d,e,d))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

# use hsplit() and vsplit()

In [205]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [206]:
np.hsplit(d,3)

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]])]

In [207]:
e

array([[28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [208]:
np.vsplit(e,3)

[array([[28, 29, 30, 31, 32, 33, 34, 35, 36]]),
 array([[37, 38, 39, 40, 41, 42, 43, 44, 45]]),
 array([[46, 47, 48, 49, 50, 51, 52, 53, 54]])]